### ISSUE TITLE
build_oval_definitions_file: add schematron validation

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#10]
I need to add schematron validation.

**Comment by DavidRies** [comment]
So, I've stopped making progress implementing schematron validation. If anyone else wants to take a look, that'd be great.

Here's what I tried:

**Take 1. Generate schematron from XSD**
Ideally, we would be able to generate the schematron xsl file from the xsds. I tried to do this using the guidance and xsls provided at http://www.schematron.com/implementation.html (see: lib_xml.py: get_schematron_xsl_from_schema) but I kept ending up with an empty string instead of an XSL document, :-1: 

**Take 2: Use Pre-generated schematron xsl**
Then, I added a pre-generated schematron xsl to the project (/oval_schemas/5.11.1/all-oval-definitions-schematron.xsl) and tried running that (see lib_xml.py: schematron_validate). That generated a "svrl" report as expected, but the report doesn't seem to have run because it doesn't contain svrl:successful-report or svrl:failed-assert elements. Then again, I'm not too familiar with this stuff.

At this point I was a couple hours in and out of ideas, so I am putting on back burner.

**Comment by solind** [comment]
If the schematron validation is successful, there will be no output from the XSL (i.e., the presence of any successful-report and/or failed-assert children implies a failure).  I know that successful-report thing is counter-intuitive.

Regards,
—David Solin
solin@farnamhallventures.com

**Comment by solind** [comment]
Sorry, there won't be "nothing", there will be no failed-assert or successful-report child elements, if the schematron validation was successful.
