### ISSUE TITLE
Add some kind of message when the repository is rebuilding?

### ISSUE THREAD

**Issue by solind** [CISecurity/OVALRepo#102]
The website should indicate when static downloads are unavailable because an update/rebuild is in-progress.  Alternatively, you could use a load-balancer or similar scheme to prevent downtime during updates.

**Comment by adammontville** [comment]
I think the recent unavailability is due to a late architectural change with respect to where the files are stored.  Under normal operating circumstances, we should be updating/rebuilding "on the side" and copying those files over when they're ready.  Stephen can confirm (or deny).

**Comment by stekel** [comment]
Thats correct. Moving forward, the file generation script shouldn't effect the website.

**Comment by stekel** [comment]
Closing...
