### ISSUE TITLE
Script: possible bug in oval definitions build script?

### ISSUE THREAD

**Issue by maheshprasad** [CISecurity/OVALRepo#103]
when building oval definitions the script returns a schematron validation error. 

![image](https://cloud.githubusercontent.com/assets/14087988/9625234/c9858d64-5154-11e5-8514-b5265ab7177a.png)

The generated oval definition file is missing the variable oval:org.mitre.oval:var:1294. But the repository contains this file in: repository\variables\oval_org.mitre.oval_var_1294.xml

**Comment by joval** [comment]
Here is the fix:

<pre>
diff --git a/scripts/lib_xml.py b/scripts/lib_xml.py
index 2e501dd..11f63f1 100644
--- a/scripts/lib_xml.py
+++ b/scripts/lib_xml.py
@@ -128,7 +128,7 @@ def get_element_metadata(filepath):
     # get all *_refs attributes
     attribute_id_refs = root.xpath("//@*[name()='definition_ref' or name()='test_ref' or name()='object_ref' or name()='state_ref' or name()='var_ref']")
     # get filter, object_reference
-    text_id_refs = root.xpath("//*[local-name()='filter' or local-name()='object_reference']/text()", smart_strings=False)
+    text_id_refs = root.xpath("//*[local-name()='filter' or local-name()='object_reference' or local-name()='var_ref']/text()", smart_strings=False)
     # combine, unique
     id_refs = set(attribute_id_refs + text_id_refs)
     
@@ -596,4 +596,4 @@ def load_standalone_element(path):
         tree = etree.parse(path)
         return tree.getroot()
     except Exception:
-        return None
\ No newline at end of file
+        return None
</pre>

**Comment by solind** [comment]
Should work now.
