### ISSUE TITLE
List of 3rd-party OVAL repositories

### ISSUE THREAD

**Issue by solind** [CISecurity/OVALRepo#104]
MITRE maintained a list of 3rd-party OVAL repositories on its repository page.  Should we do the same?  It seems like it would be nice if the community maintained a one-stop shop for all known OVAL content.

**Comment by djhaynes** [comment]
Here is the list from the MITRE website (https://oval.mitre.org/repository/about/other_repositories.html).  We should also add Canonical to the list (http://people.canonical.com/~ubuntu-security/oval/).

**Comment by stekel** [comment]
The registry page has been added to the site under the repository navigation link.
