### ISSUE TITLE
Possible Mailing List Script Issue

### ISSUE THREAD

**Issue by wmunyan** [CISecurity/OVALRepo#107]
Hi,

Currently the script 'build_oval_definitions_file.py', aborts in 2 cases,
 1. Fatal error occurred.
 2. Zero matching definitions found.

However, in case 2, i think it should create a valid oval file only with the generator tag in it, instead of aborting the script. As MITRE did on their latest update page, if no matching definitions were found (eg. http://oval.mitre.org/repository/data/downloads/latestUpdates?type=NEW_DEFS&range=DAY0_TO_3&classId=0 ). For the automated systems that invoke the python script, it might get difficult to differentiate the above 2 cases, whether the file creation failed because of case 1 or case 2.
Also the script returns 0 as the exit code from each case.

Any thoughts on this?

**Comment by DavidRies** [comment]
This seems reasonable. I'll update build scripts to output an valid OVAL definitions file with containing 0 definitions if none are found.

If there's a fatal error of some sort, then I'll have the script exit with an exit code of 1.
