### ISSUE TITLE
Netio.sys test state mismatch

### ISSUE THREAD

**Issue by gheaton** [CISecurity/OVALRepo#1149]
Multiple OVAL tests are incorrectly using oval:org.cisecurity:ste:2746 ("State matches if version is less than 6.2.9200.22202")
- oval:org.cisecurity:tst:3672 ("Check if the version of Netio.sys is less than 6.0.6002.24125")
- oval:org.cisecurity:tst:3684 ("Check if the version of Netio.sys is less than 6.0.6002.19805")
- oval:org.cisecurity:tst:3686 ("Check if the version of Ntoskrnl.exe is less than 6.1.7601.23848")

Caught in oval:org.cisecurity:def:2751; within, oval:org.cisecurity:tst:3682 is correctly using ste:2746.

**Comment by tagasulat** [comment]
Thanks for pointing that out @gheaton 
Pull request #1151 should resolve this issue.
