### ISSUE TITLE
Null versions in states

### ISSUE THREAD

**Issue by kemanik** [CISecurity/OVALRepo#1214]
This states have version 0, could you fix it?
oval:org.cisecurity:ste:971
oval:org.cisecurity:ste:972
oval:org.cisecurity:ste:975
oval:org.cisecurity:ste:977

**Comment by AlChua** [comment]
I think the versions should have been updated once the pull request has been merged. Is that correct @wmunyan ? Is this something you could fix? Thank you in advance.

**Comment by edo787** [comment]
Hello, this should now be all set.  Thanks!
