### ISSUE TITLE
Missing state

### ISSUE THREAD

**Issue by kemanik** [CISecurity/OVALRepo#1215]
Where can I find oval:org.mitre.oval:ste:4 from oval:org.cisecurity:tst:3362?

https://github.com/CISecurity/OVALRepo/commit/465ea912c68566793c91f4897b34f78a4b293d63#diff-24c63fee0fc9039773782451cb066470

**Comment by kemanik** [comment]
A lot of missing states!!!
ovalTestID oval:org.cisecurity:tst:5361 use ovalStateID oval:org.cisecurity:ste:20659
ovalTestID oval:org.cisecurity:tst:5365 use ovalStateID oval:org.cisecurity:ste:20660
ovalTestID oval:org.cisecurity:tst:5357 use ovalStateID oval:org.cisecurity:ste:20672
ovalTestID oval:org.cisecurity:tst:5363 use ovalStateID oval:org.cisecurity:ste:20674
ovalTestID oval:org.cisecurity:tst:5364 use ovalStateID oval:org.cisecurity:ste:20676
ovalTestID oval:org.cisecurity:tst:5359 use ovalStateID oval:org.cisecurity:ste:20678

**Comment by gcarps** [comment]
These missing states have been corrected and should now be represented in the tests.

**Comment by kemanik** [comment]
@gcarps Why didn't you rise the version?
