### ISSUE TITLE
Website not showing latest updates

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#131]
There are several updates to the repo in the last 30 days:
     https://github.com/CISecurity/OVALRepo/commits/master

But the website shows no updates on the latest updates page:
     https://oval.cisecurity.org/repository/latest-updates

When I update my local repo and run
     python3 web_search_definitions.py --from 20151001 --revision_type any

It shows me that there are 254 updates this month so far.

Most of them have the status "submitted" but there are also "status_change" and "modified" definitions.

**Comment by stekel** [comment]
This has been fixed.
