### ISSUE TITLE
Nonexistent states

### ISSUE THREAD

**Issue by kemanik** [CISecurity/OVALRepo#1311]
All this tests use nonexistent states:
ovalTestID oval:org.cisecurity:tst:5361 use ovalStateID oval:org.cisecurity:ste:20659
ovalTestID oval:org.cisecurity:tst:5365 use ovalStateID oval:org.cisecurity:ste:20660
ovalTestID oval:org.cisecurity:tst:5357 use ovalStateID oval:org.cisecurity:ste:20672
ovalTestID oval:org.cisecurity:tst:5363 use ovalStateID oval:org.cisecurity:ste:20674
ovalTestID oval:org.cisecurity:tst:5364 use ovalStateID oval:org.cisecurity:ste:20676
ovalTestID oval:org.cisecurity:tst:5359 use ovalStateID oval:org.cisecurity:ste:20678

**Comment by gcarps** [comment]
CIS resolved this issue.
Greg C.
