### ISSUE TITLE
Failed integrity for CIS repository

### ISSUE THREAD

**Issue by SergeyArtykhov** [CISecurity/OVALRepo#135]
Hi,

I have found missed elements in the CIS repository. For example state "oval:org.cisecurity:ste:2972" missed both GitHub and oval.cisecurity.org. 

Also missed elements:

* oval:org.cisecurity:ste:1069
* oval:org.cisecurity:ste:2791
* oval:org.cisecurity:ste:2793
* oval:org.cisecurity:ste:2972
* oval:org.cisecurity:ste:2973
* oval:org.cisecurity:ste:3251
* oval:org.cisecurity:ste:3252
* oval:org.cisecurity:tst:2210
* oval:org.cisecurity:tst:2211

This issue was occurred after PR #125 (large pull request) had been closed.
Do you have any Q&A integrity checks before closed PR?

Best Regards,
Sergey

**Comment by DavidRies** [comment]
We created a QA checklist here: https://github.com/CISecurity/OVALRepo/issues/34

And, the team did create a QA script to automate some (or all?) of the checklist items. I'm not sure if that script needs work or if the PR acceptance process needs tweaking (or both). Bill, any insight on this?

**Comment by wmunyan** [comment]
The only comments i have currently are:
- No the QA process isnt perfect
- Yes greater care needs to be taken during the PR acceptance process
- The above ID's, just looking at them, dont seem correct.  We havent had enough PRs to warrant CIS-generated ID's that high yet...The highest CIS-generated ID is somewhere in the hundreds, definitely not the thousands.  Should those be MITRE IDs?

**Comment by solind** [comment]
So far, tracking down Dale Rich's issue, I have had to add the following files to the repository:

	new file:   repository/definitions/inventory/oval_org.mitre.oval_def_19338.xml
	new file:   repository/definitions/inventory/oval_org.mitre.oval_def_24698.xml
	new file:   repository/definitions/inventory/oval_org.mitre.oval_def_24894.xml
	new file:   repository/definitions/inventory/oval_org.mitre.oval_def_28919.xml
	new file:   repository/states/linux/dpkginfo_state/0000/oval_org.cisecurity_ste_1069.xml
	new file:   repository/states/linux/dpkginfo_state/0000/oval_org.cisecurity_ste_2791.xml
	new file:   repository/states/linux/dpkginfo_state/0000/oval_org.cisecurity_ste_2792.xml
	new file:   repository/states/linux/dpkginfo_state/0000/oval_org.cisecurity_ste_2793.xml
	new file:   repository/states/linux/dpkginfo_state/0000/oval_org.cisecurity_ste_2972.xml
	new file:   repository/states/linux/dpkginfo_state/0000/oval_org.cisecurity_ste_2973.xml
	new file:   repository/states/linux/dpkginfo_state/0000/oval_org.cisecurity_ste_3251.xml
	new file:   repository/states/linux/dpkginfo_state/0000/oval_org.cisecurity_ste_3252.xml
	new file:   repository/tests/linux/dpkginfo_test/0000/oval_org.cisecurity_tst_2210.xml
	new file:   repository/tests/linux/dpkginfo_test/0000/oval_org.cisecurity_tst_2211.xml

I am not done yet.  While writing this, I found oval:org.cisecurity:ste:2974 is also missing.  These all existed in the MITRE repository.  I don't recall anyone ever deleting any files from this repository in a merge, so what happened during ETL?

Do you have any way of comprehensively checking what artifacts are missing?

**Comment by adammontville** [comment]
I'm sure we can figure out what went wrong - it seems that there are a couple of issues, though.  Some of those IDs are CIS IDs, which didn't previously exist.  If MITRE IDs are missing, that might suggest an ETL issue.  If CIS IDs are missing, that's probably an issue with PR processing.

**Comment by wmunyan** [comment]
The error, as Sergey pointed out, seemed to manifest after the processing of the large PR #125.  I found the missing MITRE definitions in a prior branch and added them back in without issue.

The erroneous CIS-generated IDs have been reconciled to their correct values in the related elements.

This commit - https://github.com/CISecurity/OVALRepo/commit/0bac4f808ae45a7d7fadf38087e86487edae8e98

performed that reconciliation.

**Comment by joval** [comment]
We're not going to need my pull request then, will we?

**Comment by wmunyan** [comment]
Closing, as it was left open after it had been resolved.
