### ISSUE TITLE
0 version for 9 elements in the MITRE OVAL repository

### ISSUE THREAD

**Issue by SergeyArtykhov** [CISecurity/OVALRepo#137]
I have found 9 elements with 0 version:

- oval:org.mitre.oval:obj:43940
- oval:org.mitre.oval:obj:44049
- oval:org.mitre.oval:obj:44102
- oval:org.mitre.oval:ste:11978
- oval:org.mitre.oval:ste:12117
- oval:org.mitre.oval:ste:38444
- oval:org.mitre.oval:tst:137360
- oval:org.mitre.oval:tst:137742
- oval:org.mitre.oval:tst:138016

I would like to propose to increase version to 1.

Best Regards,
Sergey

**Comment by wmunyan** [comment]
Fixed.
