### ISSUE TITLE
Create script that calculates oval content's schema version compatibility

### ISSUE THREAD

**Issue by blakefrantz** [CISecurity/OVALRepo#14]
Loop through all oval definitions and apply each oval version's respective xsd and schematron to detect the minimum oval version the definition is valid for. Put that information in the meta data of the definition:

```
	<definition ...>
		<metadata>	
    			<title>Windows XP Help Center Command Insertion Vulnerability</title>
			... 
			 <oval_repository>
				<min_req_schema_version>5.10.1</min_req_schema_version
```

**Comment by GunnarEngelbach** [comment]
Blake, this shows that you self-assigned this issue.  Does that mean you are writing this script?  If not, I have a bit of time right now to do it.

**Comment by blakefrantz** [comment]
This script is [complete](https://github.com/CISecurity/OVALRepo/blob/master/scripts/get_min_oval_version.py).
