### ISSUE TITLE
Strange state oval:com.hp.temp.oval:ste:20151001 (version 0)

### ISSUE THREAD

**Issue by SergeyArtykhov** [CISecurity/OVALRepo#141]
I have found strange state oval:com.hp.temp.oval:ste:20151001 and dependent on it test oval:org.cisecurity:tst:15.

Best Regards,
Sergey

**Comment by wmunyan** [comment]
Sergey, Thanks for this.  I've corrected the erroneous state, and converted it to a CIS-issued ID (ste:346)

**Comment by SergeyArtykhov** [comment]
Bill, You haven't increased version from 2 to 3 for oval:org.cisecurity:tst:15.

Best Regards,
Sergey
