### ISSUE TITLE
note element namespace differs from parent notes namespace

### ISSUE THREAD

**Issue by chris17453** [CISecurity/OVALRepo#1516]
Several tests have malformed note elements. The "note" namespace nested within the "notes" element is different than the parent and invalid. I came across this issue when de-serializing the 200meg oval definitions file into strongly typed C# objects.

The following is an example:
```
<unknown_test xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#independent" xmlns:oval="http://oval.mitre.org/        XMLSchema/oval-common-5" xmlns:oval-def="http://oval.mitre.org/XMLSchema/oval-definitions-5" check="all" check_existence="at_least_one_        exists" comment="Affected bkupexec.exe versions 3.60.1.298" id="oval:org.mitre.oval:tst:1271" version="1">
    <oval-def:notes>
        <oval:note>
              We think, but are not sure that the affected version of bkupexec.exe is 3.60.1.298 The file should be found in C:\Program Files\VERITAS\Backup Exec\NT\bkupexec.exe
        </oval:note>
    </oval-def:notes>
</unknown_test>

```
however it should be:
```
<oval-def:notes>
    <oval-def:note>
    </oval-def:note>
</oval-def:notes>
```

Links to affected tests

- [oval_tst_393](
https://github.com/CISecurity/OVALRepo/blob/f87f3fcfe28598a06b072ac795804c10b13b680b/repository/tests/independent/unknown_test/0000/oval_org.mitre.oval_tst_393.xml)
- [oval_tst_493](https://github.com/CISecurity/OVALRepo/blob/f87f3fcfe28598a06b072ac795804c10b13b680b/repository/tests/independent/unknown_test/0000/oval_org.mitre.oval_tst_493.xml)
- [oval_tst_538](https://github.com/CISecurity/OVALRepo/blob/f87f3fcfe28598a06b072ac795804c10b13b680b/repository/tests/independent/unknown_test/0000/oval_org.mitre.oval_tst_538.xml)
- [oval_tst_539](https://github.com/CISecurity/OVALRepo/blob/f87f3fcfe28598a06b072ac795804c10b13b680b/repository/tests/independent/unknown_test/0000/oval_org.mitre.oval_tst_539.xml)
- [oval_tst_1271](
https://github.com/CISecurity/OVALRepo/blob/f87f3fcfe28598a06b072ac795804c10b13b680b/repository/tests/independent/unknown_test/1000/oval_org.mitre.oval_tst_1271.xml)
- [oval_tst_2153](https://github.com/CISecurity/OVALRepo/blob/f87f3fcfe28598a06b072ac795804c10b13b680b/repository/tests/independent/unknown_test/2000/oval_org.mitre.oval_tst_2531.xml)

**Comment by solind** [comment]
This is valid in OVAL 5.11.2, as oval-definitions:notes element (deprecated) is defined as a substitution group for oval-common:notes.
