### ISSUE TITLE
Incorrect urls for cve.mitre.org

### ISSUE THREAD

**Issue by Memnarch** [CISecurity/OVALRepo#1572]
Hi,
I found several incorrect urls for cve.mitre.org.
Some start with "www" like "www.cve.mitre.org", those are not reachable and "www must be removed".
And the typo "mkitre" instead of "mitre" like "cve.mkitre.org"
And HTTP needs to change to "HTTPS" (both are reachable but i'd consider http to be outdated)

**Comment by solind** [comment]
Why not fork this repo, fix the issues you have found, and submit a pull request?

**Comment by DavidRies** [comment]
Hi @Memnarch, great catch. Thank you!

I just spot-checked a few of the www.cve.mitre.org URLs and they seem to be from multiple different authors. There were some old ones contributed by Symantec and relatively recent ones contributed by DTCC. We should all check to see that our authoring templates and/or scripts don't include this. 

I'm pretty sure that the reference@ref_url is not actually validated. It would be great if the repository moderators could enhance their QA scripts to check any supplied reference@ref_url values to ensure that they are valid URLs and that they return a 200 when queried.

Let me know if you're willing to fork and fix these issues. If not, will someone else volunteer to fix the broken CVE links?

**Comment by Memnarch** [comment]
@solind sure, but at the time i spotted them(without actuyll looking for this specifically) i was tied to several other tasks, so i thought it's best to add an issue here first. I can look into that, tomorrow
