### ISSUE TITLE
Possible incorrect file check for id="oval:org.cisecurity:def:5330

### ISSUE THREAD

**Issue by obas21** [CISecurity/OVALRepo#1589]
For Windows 2012 R2 computers, this check is looking for the version of the "Shell32.dll" file to be less than 6.3.9600.19062, but the patched version of the file from Microsoft is 6.3.9600.19061.

OVAL Check:
"Microsoft Windows Server 2012 R2 is installed" 
"Check if Shell32.dll version is less than 6.3.9600.19062"

Microsoft File Version:
Shell32.dll | 6.3.9600.19061

http://download.microsoft.com/download/C/F/3/CF32F3BA-4958-4D5C-BE39-1A98184E5D48/4338824.csv

**Comment by irapadilla** [comment]
This has been addressed through pull request #1592.

Thanks,
Ira
