### ISSUE TITLE
API Documentation Generation

### ISSUE THREAD

**Issue by GunnarEngelbach** [CISecurity/OVALRepo#16]
I thought it would be helpful to take advantage of the doc strings in the script files to generate API documentation, so I started looking into that.

Simply using pydoc -w should suffice, but I tried that against the existing source and all files returned an error message about not having doc strings -- which, to my manual examination, they do, so this is likely user error.

Still,  Sphinx (http://sphinx-doc.org/) comes highly recommended for this usage, but I have not yet taken the time to get that set up and working.

Does anybody else have opinions or suggestions?

**Comment by DavidRies** [comment]
Sphinx does look good, but I've never used any of these. It's more than possible that the initial doc strings I added aren't formatted in a "pythonic" way. Happy to revise if that turns out to be the case.

I'm not sure what we need in terms of documentation, but perhaps we don't need real API/Code docs? I think script developers can look at the code comments.

For script users (content contributors and content consumers), I think they'll just use the executable scripts and not the lib_*.py scripts. If that's the case, maybe we just needs docs for the executable scripts?

If so, they all have command line help. Maybe all we need is a good readme that explains for each executable script:
- what it's used for
- gives some examples
- tells you how to access CLI help for more details

WDYT?

**Comment by GunnarEngelbach** [comment]
My initial thought was just to assist our own productivity.  It's considerably easier to find an API using documentation than it is to search through source code.  This would also assist maintainers who come after us.

Secondarily it would be nice auto-generate nicely formatted documentation pages similar to a readme file, rather than having to make those separately.  Plus that adds an slight air of professionalism to the project which might assist in public perception.

I'm also experimenting with using the PyDev plugin for Eclipse for development.  It purports to include code completion, so that could be even handier than referencing external documentation.  I'll share impressions after I've spent more time with it.  But with, realistically, only about two weeks to go, I'll probably fall back to vi pretty soon.

Anyway, would anybody else benefit from having API documentation generated from the libraries and added to the repository?  It's not worth the time if it's only me.

**Comment by DavidRies** [comment]
That makes sense! I would use it if you made it, :) but am ok without (at least for now… we’ll see how big this thing gets).

> On Jul 10, 2015, at 10:28 AM, GunnarEngelbach <notifications@github.com> wrote:
> 
> My initial thought was just to assist our own productivity. It's considerably easier to find an API using documentation than it is to search through source code. This would also assist maintainers who come after us.
> 
> Secondarily it would be nice auto-generate nicely formatted documentation pages similar to a readme file, rather than having to make those separately. Plus that adds an slight air of professionalism to the project which might assist in public perception.
> 
> I'm also experimenting with using the PyDev plugin for Eclipse for development. It purports to include code completion, so that could be even handier than referencing external documentation. I'll share impressions after I've spent more time with it. But with, realistically, only about two weeks to go, I'll probably fall back to vi pretty soon.
> 
> Anyway, would anybody else benefit from having API documentation generated from the libraries and added to the repository? It's not worth the time if it's only me.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/CISecurity/OVALRepo/issues/16#issuecomment-120436514>.
> 

-David

--
David E. Ries
Partner
Farnam Hall Ventures 

farnamhallventures.com <http://farnamhallventures.com/>

**Comment by GunnarEngelbach** [comment]
Right-O.  There are higher priorities at the moment, but if I get a chance I'll give it a go, create a pull for the generated documents, and let you know.
