### ISSUE TITLE
Potential false negative with oval:org.mitre.oval:def:594

### ISSUE THREAD

**Issue by OvalConsumer** [CISecurity/OVALRepo#1690]
The logic for this definition appears to be 
IF
`MSN Messenger 6.2 is installed`
AND
NOT
`ANY SOFTWARE is version 6.2.0205 to 6.2.0209`

The criteria is and'ing a test that looks for any registry in the Uninstall path with a display name of `MSN Messenger 6.2` with a test that looks for a range of version numbers, but the second test looks at all software in the Uninstall path, not just MSN keys.

Specifically, a false negative should occur if
`SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Samsung Taco Party xD`
is set with `DisplayVersion` of `6.2.0205`
But
`SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Whateverthemsnkeyis`
is set with `DisplayVersion` of `6.2.0201`

**Comment by DavidRies** [comment]
Hi @OvalConsumer, I took a look at this definition and I agree. 

I also noticed that this definition was creating 14 years ago and deprecated 9 years ago. It only applies to Windows 2000 and XP, both EOL'd a long time ago.

I am surprised it's being used. I think we should consider removing these deprecated, very old definitions from the repository altogether. Or, perhaps, if there are still of use to some people, we should remove them from the master branch and put them in a deprecated branch of some sort.

Are you using this definition? If so, can you tell me a bit about your use case? And, of course, feel free to contribute a fix if you'd like!

-David

**Comment by OvalConsumer** [comment]
Thanks for the quick response! Turns out a couple of definitions that we didn't quite get were deprecated. 
I know for my own use I'd definitely appreciate deprecated definitions being in a separate branch because the sheer number of files in the repo has been an IO bottleneck for my computer - but I assume that's very likely to be a breaking change for somebody out there
