### ISSUE TITLE
Referenced variable doesn't exist. 

### ISSUE THREAD

**Issue by rakshitkitchloo** [CISecurity/OVALRepo#1699]
The following variable reference _oval:com.jovalcm.ms.cve:var:2019066200001_ used in [var:1641](https://github.com/CISecurity/OVALRepo/blob/master/repository/variables/oval_org.cisecurity_var_1641.xml) and [var:1636](https://github.com/CISecurity/OVALRepo/blob/master/repository/variables/oval_org.cisecurity_var_1636.xml) is not defined as well as is assigned some temporary id. 

This causes the OVAL file to fail when processing locally.

**Comment by DavidRies** [comment]
Hi @rakshitkitchloo, thanks for catching this. I've submitted a PR to resolve this issue (https://github.com/CISecurity/OVALRepo/pull/1701/files). 

And, we have identified the underlying issue in our content automation and resolved that so this particular problem shouldn't happen again!

**Comment by rakshitkitchloo** [comment]
Although the PR is merged but i can still see the undefined reference variable used.
How much time it's gonna take to reflect the changes.

**Comment by rakshitkitchloo** [comment]
Hey,
Any update on this?

**Comment by DavidRies** [comment]
@rakshitkitchloo, to clarify, are you saying that the issue is resolved in this repository but not in the download packages at https://oval.cisecurity.org/repository/download?

**Comment by rakshitkitchloo** [comment]
Exactly. @DavidRies 
I don't know for some reasons, those platform OVAL's aren't being updated.

**Comment by DavidRies** [comment]
Ok. I don't know exactly how often those packages are rebuilt. If you want, you can close this repo and build the packages yourself, directly from the repo. Then you wouldn't have to wait for the oval.cisecurity.org packages to build. It requires basic usage of Git and python. Instructions are here: https://github.com/CISecurity/OVALRepo/tree/master/scripts#scripts-for-content-use

**Comment by rakshitkitchloo** [comment]
Thanks @DavidRies 
We are new to this repo and the scripts being used.
So say, once i run 
`python3 build_oval_definitions_file.py -o all.windows.vulnerability.xml --family windows --class vulnerability`
it will generate platform based xml's for each windows platform?

**Comment by DavidRies** [comment]
@rakshitkitchloo, the script creates a single OVAL definitions file based on the provided filters. The command you specified above will create 1 file with all windows definitions (e.g. any definition that can be run on any Windows version). Typically, users would add a platform filter (--platform). To view platforms in current content:

```
# update the indexed
$ python3 web_update_indexes.py 

# print out the platforms
python3 web_get_repository_stats.py --platform

# then, for example, to build windows 10 vulnerability package
python3 build_oval_definitions_file.py -o windows.10.vulnerability.xml --family windows --class vulnerability --platform "microsoft windows 10"
```
