### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#17]
We need to update the readme's based on new structure etc. I suggest something like this:

**/README.md**
- short explanation of REPO purpose
- link to website
- link to /repository/README.md for more about repo organization
- link to /scripts/README.md for more about using scripts to contribute or consume content

**/repository/README.md**
- document repository organization
- link to other readmes

**/scripts/README.md**
- intro to purpose of scripts
- TOC for this file
- getting started / setup
 - dependencies description (python 3.4, etc.)
 - instructions for installing python and dependencies on various platforms
- scripts for content contributors
 - list each script with name, description/purpose, a few examples of common uses, how to access CLI help
- scripts for content consumers
 - list as above
- getting help, dealing with bugs, making RFEs
 - tell people to create an issue?
 - also, encourage people to fork, fix and PR (if they have the skillz)

**Comment by adammontville** [comment]
I'll start working on this.  There is already a /scripts/README.md file listing all the scripts we wanted to write.  I'm going to combine that with the content from the /README.md file for the time being and put new content into /README.md as suggested.  There isn't yet a /repository/README.md file, so I'll create that.

**Comment by DavidRies** [comment]
Great. You can remove the TODO list from the /scripts/README. We're using issues now.

**Comment by DavidRies** [comment]
Adam, do you want me to work on the /scripts/README.md and you can work on the root and repository?

**Comment by adammontville** [comment]
That sounds reasonable to me.

**Comment by DavidRies** [comment]
Done! Any changes can go into new tickets.
