### ISSUE TITLE
DIfference between OVAL published by CIS and other Linux Distro Vendors?

### ISSUE THREAD

**Issue by 1600** [CISecurity/OVALRepo#1707]
Canonical publish their OVAL definition file at : 
https://people.canonical.com/~ubuntu-security/oval/
Redhat publish their OVAL definition file at: 
https://www.redhat.com/security/data/oval/
etc.

I can't help but notice there are many incompatibility between CIS OVAL and theirs, while theirs seems to be more comprehensive.

Are there collaboration going on between CIS and major Linux distribution vendors on OVAL definition production?

**Comment by DavidRies** [comment]
Hi @1600, 

I'd recommend you use the Canonical feed for Ubuntu and the Red Hat feed for RHEL.

Generally speaking, I find that OVAL consumers use the vendor-provided feeds when vendors provide them and then community repositories (like this one) for platforms that lack a vendor feed. 

You also might consider making a merged feed in which you use the vendor feed and then add in any definitions present in the community feed for CVEs not covered in the vendor feed (if there are any).

-David

**Comment by 1600** [comment]
@DavidRies, thanks for pointing out CIS and Vendors are not working together. due to some imconsistency  some efforts are required to merge them together correclty.
