### ISSUE TITLE
file version bumped even if nothing changed

### ISSUE THREAD

**Issue by mirostauder** [CISecurity/OVALRepo#1716]
Why are file versions incremented if there are no changes?
e.g. commit 'CIS Processed auto-status updates 07192019'  https://github.com/CISecurity/OVALRepo/commit/844369a2b4b08696cea6b3aa988a5c3bdc2032d4
First two files have no changes, just version incremented,
there are more... this is a common sight.

**Comment by DavidRies** [comment]
HI @mirostauder, CIS can confirm the exact policy, but I think that elements are versioned when a downstream element is changed. 

For example, in a typical OVAL definition, the definition references a test which references an object and state. If the state is changed, then the upstream element versions are also incremented (the test and definition). The reasoning is that even though the test element itself wasn't changed, the logical "test" has been changed. The same goes for the definition. If it's a registry_state that checked for a value of 123 and it was changed to check for a value of 234, then the test and definition that refer to it have been changed.

Does that make sense?

-David

**Comment by mirostauder** [comment]
Ok, I get the idea...
It just seems cause an excessive churn in the git repo.
Thanks.

**Comment by DavidRies** [comment]
Yeah. It's a downside to storing relational data like oval elements in individual files in a git repo.
