### ISSUE TITLE
Duplicate entry for oval:org.cisecurity:tst:9236

### ISSUE THREAD

**Issue by glugod-aurea** [CISecurity/OVALRepo#1747]
https://github.com/CISecurity/OVALRepo/blob/master/repository/tests/windows/file_test/9000/oval_org.cisecurity_tst_9236.xml and https://github.com/CISecurity/OVALRepo/blob/master/repository/tests/windows/registry_test/9000/oval_org.cisecurity_tst_9236.xml are the same. https://github.com/CISecurity/OVALRepo/blob/master/repository/tests/windows/file_test/9000/oval_org.cisecurity_tst_9236.xml must be deleted since this is a registry test.

**Comment by DavidRies** [comment]
@glugod-aurea, 

Yes, this is odd. Good catch! Do you want to submit a PR that deletes the extra PR? If not, I would be happy to.

-David

**Comment by glugod-aurea** [comment]
I made pull request https://github.com/CISecurity/OVALRepo/pull/1748
