### ISSUE TITLE
Download xml feeds from site problem

### ISSUE THREAD

**Issue by kuPyxa** [CISecurity/OVALRepo#1867]
Hi!

This link https://oval.cisecurity.org/repository/download/5.11.2/vulnerability/ios.xml stopped working today. And I don't see any files in the "Download" section https://oval.cisecurity.org/repository/download/.

Is this a bug or a feature?

**Comment by wmunyan** [comment]
@kuPyxa Thanks for the ticket - We're taking a look at this as soon as possible!

**Comment by DavidRies** [comment]
Hi @kuPyxa, you may know this already, but you can also fork the repository and build your own packages. See the step-by-step guide here: https://github.com/CISecurity/OVALRepo/tree/master/scripts#scripts-for-content-use 

If you have any questions, just let me know.

-David

**Comment by kuPyxa** [comment]
Hi @DavidRies, yes I read about it. But it's easier to download from the link) Are you going to support this site in the future?

**Comment by DavidRies** [comment]
@kuPyxa, I think you're asking if the  https://oval.cisecurity.org/ site will be supported going forward. CIS supports that site and, as far as I know, plans to continue supporting it indefinitely. -David

**Comment by kuPyxa** [comment]
@DavidRies, that's good news. Thank you.

**Comment by wmunyan** [comment]
@kuPyxa This should be fixed now.  Please let us know if you can access your downloads and if so, please go ahead and close this ticket.  Thanks!

**Comment by kuPyxa** [comment]
@wmunyan, works, thanks a lot!
