### ISSUE TITLE
oval.cisecurity.org packages not up to date

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#1870]
It looks like the packages at https://oval.cisecurity.org/repository/download haven't been updated for over a month.

If you download https://oval.cisecurity.org/repository/download/5.11.2/vulnerability/windows.xml you will see it was generated 12/18/2020:

```
<generator>
	<oval:product_name>CIS OVAL Repository</oval:product_name>
	<oval:product_version>0.1</oval:product_version>
	<oval:schema_version>5.11.2</oval:schema_version>
	<oval:timestamp>2020-12-18T09:24:44</oval:timestamp>
</generator>
```

**Comment by adammontville** [comment]
Hi David, thanks for catching this. We’re looking into it.

**Comment by adammontville** [comment]
My team tells me that I’m packaged are building now and should be available in about an hour. 

We will be fixing alerting as well.

Adam
