### ISSUE TITLE
Not the latest Vulernabilities

### ISSUE THREAD

**Issue by liamd-dsl** [CISecurity/OVALRepo#1877]
We are running scans against definitions files that were last updated 3/23/2021. This means we are failing to identify vulnerabilities in were discovered since 3/23. This means CIS has not updated the definition files since then - the following is snippet of a definition File for MS Windows 10

<generator>
		<oval:product_name>CIS OVAL Repository</oval:product_name>
		<oval:product_version>0.1</oval:product_version>
		<oval:schema_version>5.11.2</oval:schema_version>
		<oval:timestamp>2021-03-23T08:00:18</oval:timestamp>
	</generator>

@slarchacki22  is there any ETA of when we expect def files, so we are not so far behind.

Cheers.

**Comment by slarchacki22** [comment]
We are investigating any issues with our bundle build process, and will get back with you with an answer shortly.

**Comment by slarchacki22** [comment]
The bundles have been updated so you can grab the latest now!
