### ISSUE TITLE
Repo web download by family returns empty oval_definitions element

### ISSUE THREAD

**Issue by blakefrantz** [CISecurity/OVALRepo#189]
Hi,

Repro = hit this:
https://oval.cisecurity.org/repository/download/5.11.1/compliance/red_hat_enterprise_linux_7.xml

Note that it contains no OVAL definitions. However, there are RHEL7 definitions returned by the site's search feature. This does not appear to be specific to the OVAL version (e.g. 5.11.1 vs 5.11) downloaded.

Cheers,
Blake

**Comment by stekel** [comment]
David, can you double check the web_build_oval_definitions_file is pulling the right information based on platform? It doesn't seem to be working on the latest repo update.
Thanks.

**Comment by DavidRies** [comment]
This seems to be working to me. Let me know if I missed or misunderstood something. Here's my take:

When I build RHEL 7, I get an OVAL file with 93 definitions (same if I search):
```shell
$ python3 ./web_build_oval_definitions_file.py --platform "Red Hat Enterprise Linux 7" -o ./test.out.xml
# outputs file with 93 defintions
```
However, it looks like the link you sent (above) is also filtering by class ("compliance") and when I add this to the build script (or web search), I get 0 definitions:
```shell
python3 ./web_build_oval_definitions_file.py --platform "Red Hat Enterprise Linux 7" --class compliance -o test.out.xml
# outputs file with 0 defintions
```
It looks like the RHEL 7 definitions returned are mostly "patch" class. There are a few "inventory" class as well, but no "compliance".

**Comment by blakefrantz** [comment]
That looks like the culprit. Thanks!
