### ISSUE TITLE
OVAL xml download: 500 Internal Server Error

### ISSUE THREAD

**Issue by gunnsth** [CISecurity/OVALRepo#1916]
There is an error occurs sort of randomly when downloading XML content, such as https://oval.cisecurity.org/repository/download/5.11.2/vulnerability/cisco_ios.xml

It will sometimes work fine and return a 200 response and the content, but since a few days ago it has been returning 500 Internal Server Error sometimes and failing.

So it sometimes fails

```
$ wget https://oval.cisecurity.org/repository/download/5.11.2/vulnerability/cisco_ios.xml
--2022-04-27 12:49:06--  https://oval.cisecurity.org/repository/download/5.11.2/vulnerability/cisco_ios.xml
Resolving oval.cisecurity.org (oval.cisecurity.org)... 34.203.185.151, 54.163.246.222
Connecting to oval.cisecurity.org (oval.cisecurity.org)|34.203.185.151|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2022-04-27 12:49:08 ERROR 500: Internal Server Error.
```
and sometimes works
```
$ wget https://oval.cisecurity.org/repository/download/5.11.2/vulnerability/cisco_ios.xml
--2022-04-27 12:51:00--  https://oval.cisecurity.org/repository/download/5.11.2/vulnerability/cisco_ios.xml
Resolving oval.cisecurity.org (oval.cisecurity.org)... 54.163.246.222, 34.203.185.151
Connecting to oval.cisecurity.org (oval.cisecurity.org)|54.163.246.222|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘cisco_ios.xml.1’
```
pretty much randomly it seems.

**Comment by jabuddie** [comment]
Hello,
We reviewed internally and aren't seeing the errors on our side. Let us know if there are any files that you can't retrieve at all after retrying. We will review again and work to get you the problem file as needed. I wish I could be more helpful. 
Have a good day,
Justine Buddie

**Comment by gunnsth** [comment]
Thanks. It seems like it resolved the issue, it has been working fine now.
