### ISSUE TITLE
Website Design/Branding

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#2]
Can we use CIS branding and website layout/template? Is that an acceptable approach?

**Comment by adammontville** [comment]
We can use CIS branding and website layout from our community site (https://community.cisecurity.org).  Please advise about what you need exactly.

**Comment by DavidRies** [comment]
Well, someone needs to adapt that html/css into a layout for us. They will probably need access to that site (it seems to require a username and password).

**Comment by DavidRies** [comment]
Stephen @ CIS is handling this. Adam is collaborating.

**Comment by Randal-Taylor** [comment]
The current content status label and versioning process feeds the "Latest Updates" website.  We should add something like this to the new site:

https://oval.mitre.org/repository/data/updates/latest

**Comment by blakefrantz** [comment]
Randy - issue #62 has been created to track making a latest_updates page.

I think we can close this issue per the last call. CIS is building a repo web site using their existing brand/templates.  Any objections to closing it?

**Comment by stekel** [comment]
I agree with closing...
