### ISSUE TITLE
Decompose Definitions File

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#22]
The intention is to help contributors contribute content that's in an oval definitions file.

Decompose a definitions file into component elements and put pieces into repo in correct places with correct filenames.

What to do if one or more component element files already exist? Should we canonicalize fragments and determine whether or not there's a real change? And, if there is a real change, should we prompt to increment the version number?

Optionally validate first?

**Comment by GunnarEngelbach** [comment]
I am currently working on this.

**Comment by DavidRies** [comment]
Done.
