### ISSUE TITLE
Python XML Library

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#3]
We need a Python XML library that:
- can be used x-platform (Win/OSX/*nix)
- supports schema validation
- supports schematron validation

**Comment by DavidRies** [comment]
lxml seems the most mature. Should support validation. Will not support XSLT 2, but I don't think that's a problem.

**lxml on Windows**
1. install python 3.4.3 from https://www.python.org/downloads/
2. add C:\Python34 to PATH (or wherever you installed it)
3. upgrade pip via CLI: python -m pip install -U pip
4. download unofficial Python 3.4 lxml wheel from: http://www.lfd.uci.edu/~gohlke/pythonlibs/#lxml
5. install via pip on CLI: python -m pip install <filename>

**Comment by blakefrantz** [comment]
I've moved the OSX and Windows steps above into README.md. Any reason this issue can't be closed?

**Comment by DavidRies** [comment]
Closing.
