### ISSUE TITLE
Missing object definition oval:com.dtcc:obj:106

### ISSUE THREAD

**Issue by vveselov** [CISecurity/OVALRepo#311]
The object is referenced in - 
https://github.com/CISecurity/OVALRepo/blob/2ca0788f1020d2fc89dede6ce3ba23f7ade52f7a/repository/tests/windows/file_test/0000/oval_org.cisecurity_tst_755.xml

https://github.com/CISecurity/OVALRepo/blob/2ca0788f1020d2fc89dede6ce3ba23f7ade52f7a/repository/tests/windows/file_test/0000/oval_org.cisecurity_tst_760.xml

**Comment by wmunyan** [comment]
Fixed this issue.  Thanks!
