### ISSUE TITLE
Another non-existent referenced state: oval:org.cisecurity:ste:6882

### ISSUE THREAD

**Issue by joval** [CISecurity/OVALRepo#324]
Referenced from file:
repository/tests/windows/file_test/0000/oval_org.cisecurity_tst_827.xml

I thought we had a QA process in place to maintain the referential integrity of the repository when performing merges.  Evidently there must be some flaw in the process?

**Comment by wmunyan** [comment]
Fixed.  Will continue to debug for any issues
