### ISSUE TITLE
Xml syntax error in https://github.com/CISecurity/OVALRepo/blob/347ee89e26d1b152ae580c1317b80f6b8b628e4e/repository/definitions/vulnerability/oval_org.cisecurity_def_761.xml

### ISSUE THREAD

**Issue by vveselov** [CISecurity/OVALRepo#351]
line 58 - closing quote mark is missing in test_ref attribute

<oval-def:criterion comment="Check if Win32k.sys version is less than 6.3.9600.18302" test_ref="oval:org.cisecurity:tst:1222 />

https://github.com/CISecurity/OVALRepo/blob/347ee89e26d1b152ae580c1317b80f6b8b628e4e/repository/definitions/vulnerability/oval_org.cisecurity_def_761.xml

**Comment by wmunyan** [comment]
Fixed in subsequent status update processing
