### ISSUE TITLE
Referenced variable doesn't exist oval:org.cisecurity:var:619

### ISSUE THREAD

**Issue by vveselov** [CISecurity/OVALRepo#365]
Ref id - oval:org.cisecurity:var:619

File - https://github.com/CISecurity/OVALRepo/blob/6f3694000d04d3c849058e71fb8ed0b0e08d20da/repository/objects/windows/file_object/0000/oval_org.cisecurity_obj_332.xml

**Comment by wmunyan** [comment]
Fixed -- the id was incorrect via its namespace.  Modified the cisecurity identifier to the mitre one.  The id should be oval:org.mitre.oval:var:619
