### ISSUE TITLE
Identify changes an update will make to the repository

### ISSUE THREAD

**Issue by GunnarEngelbach** [CISecurity/OVALRepo#37]
For any given update, show a list of all files that it will change in the repository.

This is expected to be a work in progress.  Initial functionality will make an best attempt to not show files that do not change, but can still possibly produce a large list of files.

Assigning this to myself.

**Comment by solind** [comment]
How is this different from git diff?

**Comment by DavidRies** [comment]
A couple notes/ideas for this:
- I think it should show the diff between the current working directory and 
 - the upstream master (CISecurity/OVALRepo/Master) HEAD, if on a fork
 - the master branch HEAD if not on a fork (CISecurity/OVALRepo)
- I assume you're going to use GIT for this (it has these features built in) via lib_git.py?

**Comment by GunnarEngelbach** [comment]
A git diff is a decent tool for identifying what files changed and what 
items within those files changed, and has a decent interface for 
displaying that information.

But it has no knowledge of how that relates to the relationships between 
OVAL elements.

The primary purpose I have in mind is to map out all the elements that 
will be affected by an update.  The first step is to identify which 
files in an update actually changed, then build a map of all upstream 
and downstream elements that are affected by that -- directly and 
indirectly.

As we talked about earlier, I may limit this only to the identifying 
which parent definitions are in the direct upstream paths.  That's a 
simple tree walk.

**Comment by DavidRies** [comment]
There's already a script and library methods to find all elements related to an element (upstream and/or) downstream. See get_related_elements.py.

**Comment by GunnarEngelbach** [comment]
I hadn't seen that, excellent.

Although, what it takes as an argument is an OVAL ID, not a repository submission.  That leaves it up to the reviewer to find out all the OVAL IDs in a submission via someother method (cutting and pasting from the git diff?) and run the script separately for each.

**Comment by DavidRies** [comment]
Yes. We still def need the script that you're working on. It should determine the oval Ids in git diff between working dir and upstream master head. We don't have that part. But then, you could use get_related_elements.py, build_oval_definitions_file.py and validate_oval_definitions_file.py (or the lib methods used in them) to get the affected defs, compile them into a file and validate.

**Comment by GunnarEngelbach** [comment]
If you don't mind, I'm going to move parts of what is in get_related_elements into lib_repo as a static method to minimize repitition -- and possibly do the same with some of the other scripts.

**Comment by DavidRies** [comment]
Sure!  

get_related_elements.py really just calls elements_index.find_downstream_ids() and downstream_ids = elements_index.find_upstream_ids(). The rest is parsing arguments and output.

I just wrote it to demo how to use those two find methods because I knew we’d need them.

lib_repo is supposed to be an abstraction for accessing files, naming conventions, etc. used in the repository-specific OVAL files. “Find” type methods should be in lib_search.

That said, go for it!

-David



> On Jul 16, 2015, at 8:44 AM, GunnarEngelbach <notifications@github.com> wrote:
> 
> If you don't mind, I'm going to move parts of what is in get_related_elements into lib_repo as a static method to minimize repitition -- and possibly do the same with some of the other scripts.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/CISecurity/OVALRepo/issues/37#issuecomment-121960467>.
> 

-David

--
David E. Ries
Partner
Farnam Hall Ventures 

farnamhallventures.com <http://farnamhallventures.com/>

**Comment by DavidRies** [comment]
Gunnar and I have done this!
