### ISSUE TITLE
Do we need a data model?

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#4]
The other outstanding question is if we should consider using a code generation library for the base classes or forego it. Some base classes with (de)serialization support might be ideal. A couple XSD->Python libraries exist. Does anyone have experience with either?

http://pythonhosted.org/generateDS/
https://pypi.python.org/pypi/PyXB/1.2.4 

Thoughts?

**Comment by DavidRies** [comment]
I don't think we need this, but haven't given it much thought. What would we use this data model for?

**Comment by blakefrantz** [comment]
After reviewing #5 I'm not sure we need this either as the libraries will provide a standard interface for reading/writing/serializing the oval content.

**Comment by DavidRies** [comment]
It seems like we're off and running without a data model, so I'm closing this. If anyone thinks we should discuss further, feel free to re-open.
