### ISSUE TITLE
Missing xmlns shell:shellcommand_*

### ISSUE THREAD

**Issue by markveerman** [CISecurity/OVALRepo#434]
Generate CIS Benchmark Probes for CentOS_Linux_7 v2.1.0
Referenced entity not found: oval:org.cisecurity.benchmarks.o_centos_centos:tst:10169

I believe this may be due to a change from unix:login_shell perhaps? The shell:shellcommand_* is used in the following benchmarks.
CIS_Amazon_Linux_Benchmark_v2.0.0-oval.xml
CIS_CentOS_Linux_6_Benchmark_v2.0.1-oval.xml
CIS_CentOS_Linux_7_Benchmark_v2.1.0-oval.xml
CIS_Oracle_Linux_6_Benchmark_v1.0.0-oval.xml
CIS_Oracle_Linux_7_Benchmark_v2.0.0-oval.xml
CIS_Red_Hat_Enterprise_Linux_6_Benchmark_v2.0.1-oval.xml
CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v2.1.0-oval.xml

**Comment by wmunyan** [comment]
Mark, 
I'm going to close this issue and respond via email as I am not sure it's an OVAL repo issue; more of a CIS content issue.
Cheers, 
-Bill M.
