### ISSUE TITLE
Referenced test is not in repository - oval:org.mitre.oval:tst:115787

### ISSUE THREAD

**Issue by vveselov** [CISecurity/OVALRepo#463]
The test ioval:org.mitre.oval:tst:115787 s referenced by several definitions, but not submitted into the repository.

**Comment by wmunyan** [comment]
The file for that test is located in the repository in the following location:
`repository\tests\windows\file_test\115000\oval_org.mitre.oval_tst_115787.xml`

The following definitions utilize the test:
`oval:org.mitre.oval:def:25054`
`oval:org.mitre.oval:def:24987`
`oval:org.mitre.oval:def:24927`
`oval:org.mitre.oval:def:24979`
`oval:org.mitre.oval:def:25006`
`oval:org.mitre.oval:def:25235`

Cheers, 
-Bill M.
