### ISSUE TITLE
Transition Team Agenda - 07/22/2015

### ISSUE THREAD

**Issue by wmunyan** [CISecurity/OVALRepo#48]
Potential Agenda Items for 7/22/2015 Transition Team Call

- Team Updates (5 min)
- Discussion (50 min)
   - Issue #34 - Comprehensive QA Wishlist
   - Issue #40 - ID Namespaces
   - Issue #41 - Version Number Guidelines
   - Issue #50 - pilot test repo by 7/29
   - Issue #2 - website update 
- Etc and next steps (5 min)

**Comment by DavidRies** [comment]
Done! Next steps in other tickets.
