### ISSUE TITLE
Develop code to validate full oval for each OS

### ISSUE THREAD

**Issue by geriamir** [CISecurity/OVALRepo#496]
Hi,

I'm keep getting invalid references between elements in full windows definitions.
There needs to be something that run every so often and deliver the status of the integrity of the repository.
For instance, right now the repository for windows is broken because there is a reference to 'oval:org.cisecurity:tst:8267' in 'oval:org.cisecurity:def:1073' but the test was deleted and removed from other definitions.

Best regards,
Amir

**Comment by wmunyan** [comment]
Amir, 
Thanks for the feedback.  I have corrected the bad ID reference in def:1073.  I will add a ticket to our internal development schedule to periodically check the integrity of the repo.

Cheers, 
-Bill M.
