### ISSUE TITLE
Script Modules (libraries)

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#5]
Let's use this topic as a place to identify the libraries we want to make and their contents (until we have the actual libraries in place).

Here's an initial thought:
- lib_xml.py: methods to perform validation, read XML in file into Python object and vice versa, etc.
- lib_repo.py: methods to find/access files in the repo by id, etc. so scripts can operate without knowledge of repo structure
- lib_git.py: methods that use git via https://github.com/gitpython-developers/GitPython to figure out which OVAL element files have been updated and need to be validated, version-rev’d, etc.
- lib_search.py: methods to search repo, e.g. for defs with a specific class; or for things that reference a specific OVAL id
- lib_markup.py: methods useful for generating documentation markup

???

**Comment by blakefrantz** [comment]
Should lib_repo and lib_search be combined? It sounds like the intent of lib_repo is to insulate other scripts from repo structure changes. It seems a search feature might need to know the structure. What's your take?

What's your take on adding something like lib_bundle that sits on top of lib_search/lib_repo to create, for example, the family/class/version zip downloads.

**Comment by DavidRies** [comment]
Sounds good. We can split them up later if we want.

We can make a lib_bundle, but I was thinking that would be a script that uses the other libs, as follows:
- uses lib_search/lib_repo to get all the oval ids and file paths it needs
- uses lib_xml to write an oval file based on the file paths

**Comment by DavidRies** [comment]
Let's charge forward and see what comes out the other side!

**Comment by DavidRies** [comment]
This is underway!
