### ISSUE TITLE
Pilot Test Repo

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#50]
We should attempt to get SecPod, HP, ALTX-SOFT and a handful of consumers to pilot-test making contributions and consuming content as soon as possible.

**Comment by GunnarEngelbach** [comment]
Prior to that we should simulate a contribution, both via pull request and email submission.

**Comment by DavidRies** [comment]
We are recruiting pilot testers for testing starting Tuesday 7/28:
- CIS: will recruit SecPod, HP, ALTX-SOFT
- Threatguard: will pilot test consuming content
- Joval: will recruit private content consumers
- Blake: will reach out to openscap community for pilot testers

**Comment by blakefrantz** [comment]
seems like this can be closed.

**Comment by wmunyan** [comment]
Agreed.
