### ISSUE TITLE
Randy: review status guidelines and make recomendation

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#52]
Randy will review status guidelines and make a recommendation.

**Comment by DavidRies** [comment]
https://oval.mitre.org/repository/about/stages.html

**Comment by Randal-Taylor** [comment]
It appears that MITRE revised these guidelines several times until they got a solid process.  We could certainly automate the process as they have outlined it.  A few things that jump out at me:

- Versioning and status labeling are tightly linked.  When a status label of a definition changes, the version number of the definition and all associated components get incremented.

- New content is contributed to the repository with version of "0".

- When a change is made to an "accepted" definition, the status gets changed to "interim" for two weeks

- When the status label of a definition changes, that definition shows up on the "Latest Updates" webpage (that lists new definitions and modified definitions)

So I recommend we adopt the process as outlined by MITRE and automate it.  We also must add the "Latest Updates" webpage as it is a great place for the users to see new and changed definitions.

**Comment by DavidRies** [comment]
Ok, great. I will create a ticket to script this.
