### ISSUE TITLE
Rebuild a full repository with all files

### ISSUE THREAD

**Issue by security-database** [CISecurity/OVALRepo#520]
Hello All

This repo is really interesting. We are actually mirroring the old Mitre Repository (https://www.security-database.com/oval.php) for some years. We know it will not be updated, so we search a new way. It seems that mirroring the new one will not be an option ;). We need, for that to rewrite totally our mirroring scripts.

We have played a little with scripts on this repo and would like to know if there is a way to:
- Have a list of Oval schema number (5.xx -> x.xx?)
- Automatically rebuild all possibility of files like in the repo? We actually play with: web_get_repository_stats.py --family / --platform and so to have a list but we think it's not the best way.
- Have an index with all file generated to be able to update our database.
- What's difference between:
  - build_oval_definitions_file.py
  - web_build_oval_definitions_file.py

Do you have any tips about that?

**Comment by wmunyan** [comment]
Thanks very much for the questions!

- Have a list of Oval schema number (5.xx -> x.xx?)
[WKM] Do you mean that you'd like to generate definitions based on schema version?  If that is the case, I would suggest looking at the "build_oval_definitions_file.py" script.  There are command-line options there to specify a max schema version.

- Automatically rebuild all possibility of files like in the repo? We actually play with: web_get_repository_stats.py --family / --platform and so to have a list but we think it's not the best way.
[WKM] I am not sure I completely understand this question.  Do you want to build a single file containing the entire repository of definitions?  If that's the case, you can use the "build_all_oval_definitions.py" script.

- Have an index with all file generated to be able to update our database.
[WKM] This sounds like you would like a changelog indicating new/updated definitions?  I feel like we rely on the commit logs in github to track which items have changed or been added.

- What's difference between:
    - build_oval_definitions_file.py
    - web_build_oval_definitions_file.py
[WKM] The difference between those two scripts is that the "web" version is used by the CIS OVAL Repository website (oval.cisecurity.org/repository) to generate and post versions of the definitions for public download.

Hope that helps!
Cheers, 
-Bill M (CIS)

**Comment by security-database** [comment]
Hello @wmunyan 

To be simple, we want to make a full mirror of the CIS repo. By That we mean generate automatically all xml for all bulk - platform - family and so on. (xxx xml files).

Thanks
Benjamin

**Comment by wmunyan** [comment]
Excellent.  The best script to use for that is the "build_oval_definitions_file.py".  That contains enough command line options to build the full OVAL definitions file, by family, by platform, by schema, or by any combination of those attributes.
Cheers,
-Bill M.

**Comment by security-database** [comment]
Hello @wmunyan

Yes, i'm sure ;) But we need some automation.
Is there any way to list all possibility ?
  * list all Oval schema possibility
  * list all available Platform
  * list all available family
  * ...

That will be necessary to make a script and loop through all of them

-B

**Comment by wmunyan** [comment]
in essence, a script that will do
```
for each schema 
  for each family
    for each platform
      build_oval_definitions [schema] [family] [platform] 
```
Is this what you're looking for?

**Comment by security-database** [comment]
Yes, i think so ;)
we need to make a python script for that ;) hehe

It will be a little more complex because we want to generate each file for each OVAL version.
But yes. It will do the job.

**Comment by DavidRies** [comment]
Hi, you can definitely generate files just like those that appear on the website. These scripts are the same ones used by the site for that purpose!

Here are some tips:

- You can use lib_oval.get_schema_versions() to get a list of all schema versions in the OVAL repo
- You can use web_get_repository_stats.py to get all the Platforms, Products, etc. in the repo
- You can then web_build_oval_definitions.py to build packages for each combination of schema version, platform, product, etc. that you want!

A couple tips about the "web_" files:

- They were designed to be called via the command line by another script (e.g. a PHP script) so they return JSON.
- You should run web_update_indexes.py once before running any of the other web_ scripts to update the index. This is not necessary with the non-"web_" scripts; they update the index themselves.

**Comment by security-database** [comment]
Thanks a lot @DavidRies 

It's perfectly clear.

Just to say that we have open an issue on web_get_repository_stats.py that fail with -a actually.

-B
