### ISSUE TITLE
get_min_oval_version.py lxml.etree.XMLSchemaParseError: local union type line 461

### ISSUE THREAD

**Issue by security-database** [CISecurity/OVALRepo#521]
A little error when
`python3 get_min_oval_version.py -a`

INFO: Schema Path is /OVALRepo/oval_schemas/5.11.1/all-oval-definitions.xsd
Traceback (most recent call last):
  File "get_min_oval_version.py", line 181, in <module>
    main()
  File "get_min_oval_version.py", line 141, in main
    result = determine_def_min_version(defpath, definitions_index, elements_index, args['update'])
  File "get_min_oval_version.py", line 94, in determine_def_min_version
    lib_xml.schema_validate(tree, schema_path_cache[schema_version])
  File "/OVALRepo/scripts/lib_xml.py", line 164, in schema_validate
    schema_cache[schema_path] = etree.XMLSchema(etree.parse(schema_path))
  File "xmlschema.pxi", line 87, in lxml.etree.XMLSchema.__init__ (src/lxml/lxml.etree.c:174910)
lxml.etree.XMLSchemaParseError: local union type: A type, derived by list or union, must have the simple ur-type definition as base type, not '{http://oval.mitre.org/XMLSchema/oval-system-characteristics-5}(NULL)'., line 461

**Comment by DavidRies** [comment]
Hi! That's a strange error. It seems the python xml package lxml doesn't like one of the schemas. 

I don't get an error running this on my machine. Here are a couple ideas:

- ensure your schemas haven't been corrupted somehow by running git diff
- try running the version of lxml that I'm running lxml==3.4.4

As a side note... you shouldn't need to use this script to generate packages. This is primarily for content authors and repository maintainers to help them add metadata to definitions specifying the minimum schema version required to fully support a definition.

**Comment by security-database** [comment]
pip search lxml

```
lxml (3.6.4)
  INSTALLED: 3.4.4
  LATEST:    3.6.4
```
No problem with git diff

Thanks for the side note ;)

**Comment by DavidRies** [comment]
Well, I have no idea why this doesn't work on your machine and does on mine.

Do you need to use this script?

**Comment by security-database** [comment]
nop ;) Just helping and open a case when found an error ;)

**Comment by DavidRies** [comment]
Ok, that is helpful. Thanks! However, for the time being, I am going to close this ticket because I cannot reproduce the error. If some encounters this error and needs to use the script, pls re-open!
