### ISSUE TITLE
Script:  Create predefined bundles

### ISSUE THREAD

**Issue by GunnarEngelbach** [CISecurity/OVALRepo#53]
A single script that creates the predefined categories (id est, all Windows definitions, all Solaris definitions) that are to be available via the web site.

Caveat:  if it is performant for these to be generated dynamically by the web site, then there won't be a need for a script to pregenerate them.

**Comment by DavidRies** [comment]
Stephen, just let us know what you need on this one.

**Comment by stekel** [comment]
The predefined bundles are being generated via a cron for now, so I'll close this ticket.

I'll create another ticket to update the bundles to on-demand and drop it into the backlog milestone.
