### ISSUE TITLE
Create static urls for oval.xml and oval.xml.zip by schema version

### ISSUE THREAD

**Issue by blakefrantz** [CISecurity/OVALRepo#54]
For example:
http://oval.mitre.org/rep-data/5.10/org.mitre.oval/oval.xml
http://oval.mitre.org/rep-data/5.10/org.mitre.oval/oval.xml.zip

Where "5.10" would be replaced with each OVAL version between 5.3 and 5.11.1

The files behind these urls would be autogen'd daily.

**Comment by stekel** [comment]
All oval definitions by version (and zip files) are now being generated for the download page.

**Comment by blakefrantz** [comment]
I thought this was blocked on writing the bundle-by-oval-version code. Did someone write that already?
