### ISSUE TITLE
Missing Objects in oval_org.cisecurity_obj_421.xml

### ISSUE THREAD

**Issue by tagasulat** [CISecurity/OVALRepo#540]
![oval_org cisecurity_obj_421](https://cloud.githubusercontent.com/assets/15995710/19514184/417a7972-9625-11e6-92f6-78242ac3af96.JPG)

The following objects cannot be found in the repository: 
oval:org.cisecurity:obj:4234
oval:org.cisecurity:obj:4235

**Comment by BerndEggenmueller** [comment]
I got the same issue, can you fix it quickly that I can execute scans?

**Comment by wmunyan** [comment]
Fixed.  This could take some time to be refreshed in the downloadable bundles from the OVAL repository website.
