### ISSUE TITLE
Find Affected Error

### ISSUE THREAD

**Issue by wmunyan** [CISecurity/OVALRepo#58]
Running:
> python find_affected.py --remote origin --outfile C:\_Development\oval_repository\submissions\46\reconstructed.xml

Receiving the following error:
Traceback (most recent call last):
  File "find_affected.py", line 124, in <module>
    main()
  File "find_affected.py", line 56, in main
    elements_index = lib_search.ElementsIndex(message)
  File "C:\_Development\OVALRepo\Forks\wmunyan\OVALRepo\scripts\lib_search.py",
line 382, in __init__
    super().__init__(message_method)
TypeError: super() takes at least 1 argument (0 given)

**Comment by DavidRies** [comment]
Thanks, Bill. I'll take a look.

**Comment by DavidRies** [comment]
Bill, any chance you're using python 2? Can you run:
```
python -V
```

**Comment by wmunyan** [comment]
I'm putting the C:\Python34 folder at the front of my path explicitly:
    > SET PATH=C:\Python34;%PATH%
    > python -V
    Python 3.4.3

**Comment by DavidRies** [comment]
Hi Bill, that's very strange. I cannot reproduce this. This error is supposed to happen in Python 2.x only.

**Comment by DavidRies** [comment]
I just made a change to call super in a way that is supposed to work in python 2.x and 3.x and resolve this error. Can you pull and try again?

**Comment by DavidRies** [comment]
Marking resolved. Re-open if it's not.
