### ISSUE TITLE
Repository content folder structure

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#6]
I really think we should group all elements (except definitions) into folders named by the test/object/state/variable “predicate”. By “predicate”, I mean the part before “_test/_object/etc.” (e.g. “file_effective_rights” for a “file_effective_rights_test”). Doing so would really help reduce the number of files we need to search in many cases. For example, if I am trying to find all tests that reference a file_effective_rights_object, I would just need to search in tests/file_effective_rights/ folder as opposed to the whole tests folder.

**Comment by blakefrantz** [comment]
That seems reasonable. Below are some quick stats on the number of predicates for oval tests and objects. It looks like we'd still have some content-heavy folders, but it's an improvement.

  count | test                       
-------- | ----------------------------
  65    | cmdlet_test                
  49040 | dpkginfo_test              
  3     | family_test                
  9891  | file_test                  
  11    | inetd_test                 
  24    | inetlisteningservers_test  
  1     | isainfo_test               
  110   | line_test                  
  8     | metabase_test              
  77    | package_test               
  340   | patch54_test               
  923   | patch_test                 
  59    | plist510_test              
  3     | plist_test                 
  28    | process_test               
  2385  | registry_test              
  51366 | rpminfo_test               
  3     | service_test               
  8     | smf_test                   
  118   | textfilecontent54_test     
  30    | textfilecontent_test       
  61    | uname_test                 
  6     | unknown_test               
  136   | variable_test              
  2121  | version55_test             
  176   | version_test               
  74    | wmi57_test                 
  21    | wmi_test                   
  8     | xmlfilecontent_test        



  count  |  object                        
-------- | -------------------------------
  1      |  cmdlet_object                 
  13605  |  dpkginfo_object               
  2      |  environmentvariable58_object  
  1328   |  file_object                   
  11     |  inetd_object                  
  24     |  inetlisteningservers_object   
  7      |  line_object                   
  5      |  metabase_object               
  75     |  package_object                
  336    |  patch54_object                
  806    |  patch_object                  
  7      |  plist510_object               
  3      |  plist_object                  
  28     |  process_object                
  1477   |  registry_object               
  17100  |  rpminfo_object                
  3      |  service_object                
  8      |  smf_object                    
  69     |  textfilecontent54_object      
  30     |  textfilecontent_object        
  46     |  variable_object               
  74     |  wmi57_object                  
  17     |  wmi_object                    
  3      |  xmlfilecontent_object         

 If folks want to reproduce these numbers for some reason, do this:

```
$ cd oval_repository/repository/tests
$ for file in $(ls -1);do predicate=$(egrep "^</" $file | tr -d '</>'); echo $predicate >> /tmp/predicates/tests_${predicate}; echo -n .; done
$ for i in $(ls -1 /tmp/predicates/tests_*); do wc -l $i; done
```

**Comment by solind** [comment]
Just FYI, guys, there are instances where predicate names are duplicated across different platform schemas.  The new Cisco schemas are riddled with these, but it also happens with windows:process_test, unix:process_test, and a few others.

Is it important/desirable to separate out these duplicates in the folder structure?

**Comment by DavidRies** [comment]
I think that for clarity, it would be nice to put predicates under schema "short name", e.g.:
````
/<tests | objects | states | variables>/<windows | linux | cisco ios | etc.>/<predicate>/<oval id>...xml
````

**Comment by GunnarEngelbach** [comment]
That's reasonable, but still won't help the predicates that have a lot of usage right now and are bound to grow rapidly. dpkginfo, fileinfo, and rpminfo, for example.

Two possibilities for an additional level in the hierarchy:
 1)  Use the contributor part of the OVAL ID
 2)  Use a modulus of the index portion of the OVAL ID to limit the number of files per directory

#1 Is more meaningful to direct human browsing of the repository but that's of limited utility.  And it will likely not be helpful in the goal of reducing the number of files per directory.

#2 enforces an absolute limit on the number of files per directory.

At this point and example path would look like

/tests/linux/rpminfo/10000/oval:org.mitre.oval:test:5555.xml

That's a depth of 4 directories before getting to any files, which if human browsing is a goal creates a bit of a pain.  Two suggestions for reducing the number of directories:

1)  combine the platform/predicate into a single directory name, ala "linux:rpminfo"

2) Skip the platform and predicates altogether, since usage of the index modulus will guarantee a limited number of files per folder.  As a possible added benefit to this scheme, all the information necessary to determine the path is available in the OVAL ID itself.

**Comment by blakefrantz** [comment]
After our last call, it sounds like the current proposed directory structure is:
```
scripts/
repository/
repository/definitions 
repository/[oval_type]
repository/[oval_type]/[schema_short_name]
repository/[oval_type]/[schema_short_name]/[predicate]
```
* [oval_type] == object/state/variable/definition
* [schema_short_name] == windows/cisco ios/independent/...
* [predicate] == process_object/uname_test/...

Note the absence of directories for housing the lists of oval things.

I have no objections to this layout and see it as an improvement to what we currently have. The only slight alternative we might want to consider is swapping the positions of [oval_type] and [schema_short_name]. If I'm browsing a file structure for an oval thing it seems more natural to start with the platform/schema_short_name, like windows or linux, vice the oval-type.

**Comment by wmunyan** [comment]
I think its necessary to define the intent of the directory structure.  My initial structure makes it very simple to generate the static downloads, for example.  Other proposed structures make it easier to implement searching such as a search "by item", such as finding all <registry_object>'s.  Other proposed solutions are meant to make it easier for a human to browse the directory structure.

So what is the real intent?  
Is the intent to facilitate generating content for users to download?  If so the current structure works perfectly, and we'll provide scripts and downloads similar to the current MITRE site to do that.

Is the intent to facilitate searching for content?  If so, it seems like David R. had some indexing built into some scripts to be posted and using something like a lucene to perform some searching.  If there's indexing built into the scripts, is a directory structure change necessary?

Is the intent to facilitate a user navigating the repo?  Was the intent to ever have that be an option?  No one can willy-nilly browse the current repository; we need to search first.  It would seem to me that ease of user-initiated file system navigation should be the lowest priority.

I will freely admit that the serialization code and file structure I built was intended to make generating the bulk downloads easy.  Thats the purpose of the various class folders and platform folders with the text files containing definition ids.  To generate particular downloads, one only has to grab the definitions from those files and build away.

**Comment by DavidRies** [comment]
I agree, Bill: we need to decide on the purpose. Initially, I agreed with you about making build process easy.

However, now that we're into the build scripting and using an index, I don't think we need to consider the search and generation. Scripts and the index will take care of these.

That liberates us to organize it to facilitate users navigation the repo and I vote for that. I think it will make the repo look more usable and organized to people when they first start using it.

With that in mind, I support Blake's structure (above) with the addition of breaking definitions down by class:
```
scripts/
repository/
repository/definitions/[class]
repository/[oval_type]
repository/[oval_type]/[schema_short_name]
repository/[oval_type]/[schema_short_name]/[predicate]
```

**Comment by GunnarEngelbach** [comment]
I don't think human navigation of the repository is of high priority.  Just my hunch that direct browsing of the individual component files is just not something that is going to happen very often.

My biggest concern is in the performance of using the repository, be it for git push/pulls, building content bundles that match search criteria, and so on.  And my experience is that limiting the number of files per directory is one of the largest factors that can help.

**Comment by blakefrantz** [comment]
+1 to @DavidRies.

Tangent: @DavidRies is the plan to update https://github.com/CISecurity/OVALRepo/blob/master/scripts/lib_repo.py#L52 to grab the oval-thing's path from the index?

**Comment by solind** [comment]
Git couldn't care less about the number of files per directory. It's the total number of files that dictates the size of the Git index.

There are OS limitations to the max number of files per directory, however, the limit for human usability is much lower.

**Comment by DavidRies** [comment]
Actually, the git web UI has a limit on the number of files/folder it will display (1,000):
	https://github.com/CISecurity/OVALRepo/tree/master/oval_repository/repository/objects <https://github.com/CISecurity/OVALRepo/tree/master/oval_repository/repository/objects>

The proposed changes won’t get all folders down to 1,000 files, but it will help.



> On Jul 8, 2015, at 3:33 PM, David Solin <notifications@github.com> wrote:
> 
> Git couldn't care less about the number of files per directory. It's the total number of files that dictates the size of the Git index.
> 
> There are OS limitations to the max number of files per directory, however, the limit for human usability is much lower.
> 
> Sent from my iPhone
> 
> > On Jul 8, 2015, at 11:09 AM, GunnarEngelbach <notifications@github.com> wrote:
> > 
> > I don't think human navigation of the repository is of high priority. Just my hunch that direct browsing of the individual component files is just not something that is going to happen very often.
> > 
> > My biggest concern is in the performance of using the repository, be it for git push/pulls, building content bundles that match search criteria, and so on. And my experience is that limiting the number of files per directory is one of the largest factors that can help.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> > 
> —
> Reply to this email directly or view it on GitHub <https://github.com/CISecurity/OVALRepo/issues/6#issuecomment-119723620>.
> 

-David

--
David E. Ries
Partner
Farnam Hall Ventures 

farnamhallventures.com <http://farnamhallventures.com/>

**Comment by GunnarEngelbach** [comment]
And the primary concern with number of files/directory isn't about github -- it's a concern for everybody who needs to work with the content once they've made a local copy of the repository to their workstations.

**Comment by GunnarEngelbach** [comment]
In any case, I think we've hashed this enough to poll for majority opinion and get moving on this.

My preference is

**Definitions:**
> definitions/classification

**All other elements:**
> repository/[oval_type]/repository/[oval_type]/[schema_short_name]/[predicate]/[index_modulus]

**Comment by wmunyan** [comment]
New repository content has been serialized using the folder structure:
`repository/definitions/[class]`
and
`repository/[oval_type]s/[schema_short_name]/[predicate]/[index_modulus]`

For example:
`repository/objects/linux/rpminfo_object/24000/oval_org.mitre.oval_obj_23691.xml`

comments/questions/constructive criticisms welcome.

**Comment by DavidRies** [comment]
Closing because this looks done!

If anyone wants further changes to the structure, please create a new ticket.
