### ISSUE TITLE
Potential string concat issue in oval_decomposition.py

### ISSUE THREAD

**Issue by adammontville** [CISecurity/OVALRepo#64]
Scenario:
* I have a definitions file on my desktop (oval_org.mitre.oval_def_5275.xml)
* From my local clone's `scripts` directory, I ran `python3 oval_decomposition.py ~/Desktop/oval_org.mitre.oval_def_5275.xml`, which failed with a `FileNotFoundError`

The file it was looking for is: `/Users/adammontville/Documents/CIS Local/adammontville/OVALRepo/repository//Users/adammontville/Documents/CIS Local/adammontville/OVALRepo/repository/definitions/compliance/oval_org.mitre.oval_def_5275.xml`

Seems as though the scripts are expecting whole definitions files to exist in `OVALRepo/repository`.  Is that right? 

Actually, even when I put the OVAL file in the `repository` directory, it's not parsing because line 161 of `lib_oval.py` is true.

**Comment by GunnarEngelbach** [comment]
That particular script is, yes.  And its only usage is to pull apart a 
separate oval_definitions file and write the component elements into the 
proper places in the repository.

Once it is in the repository a separate script, submission_qa.py, would 
be used to run through all of the QA steps.

If it is also necessary to process standalone element files into the 
repository, that would be an easy script to add.

**Comment by adammontville** [comment]
So, if I build a definitions file based identifying def 5275 and make a change to that definitions file, then I should be able to run `oval_decomposition.py`?  Because that's what's not working for me.

**Comment by GunnarEngelbach** [comment]
If, by "definitions file" you mean one that has the structure:

<oval_definitions>
   <definitions>
     <definition id="blah">
     </definition>
   </definitions>
</oval_definitions>


Then yes, that is what that script should work for.

What kind of error message are you getting?  Your first post said 
something about a file not found error with a questionable path. That 
looks like something different.  If that's what's happening, try it 
using a path name that doesn't start with a tilde -- it almost seems 
that shell expansion of the argument is the problem.

**Comment by GunnarEngelbach** [comment]
On 7/28/2015 8:10 AM, adammontville wrote:
>
> Scenario:
>
>   * I have a definitions file on my desktop
>     (oval_org.mitre.oval_def_5275.xml)
>   * From my local clone's |scripts| directory, I ran |python3
>     oval_decomposition.py ~/Desktop/oval_org.mitre.oval_def_5275.xml|,
>     which failed with a |FileNotFoundError|
>
> The file it was looking for is: |/Users/adammontville/Documents/CIS 
> Local/adammontville/OVALRepo/repository//Users/adammontville/Documents/CIS 
> Local/adammontville/OVALRepo/repository/definitions/compliance/oval_org.mitre.oval_def_5275.xml|
>
> Seems as though the scripts are expecting whole definitions files to 
> exist in |OVALRepo/repository|. Is that right?
>

Misread this.

No, the script most emphatically does *not* expect anything in the 
repository itself to be an oval_definitions file.

**Comment by adammontville** [comment]
It looks like we should comment out like 109 of `oval_decomposition.py`.

**Comment by GunnarEngelbach** [comment]
Why?  The whole point is to put a submission into the repository so the 
QA script can be run against it.

My understanding from the last time we talked is that the default 
submission process would be via processing a pull request, so that is 
what the QA script was written to deal with.  This script is just an 
interim to be able to process submissions made via the current method.  
It should be able to handle separate elements, though.

It also needs to do a couple other things:

1) Check to see that the local repository is clean so the QA script 
isn't attempting to process multiple changes
2) For each element not only check to see if it already exists, but 
determine if there aren't any meaningful changes

**Comment by wmunyan** [comment]
What we discovered is that line 109 of `oval_decomposition.py` is concatenating the "repo_root" with the filepath.  However, when the filepath is constructed using `lib_repo.get_element_repository_path(e)`, it is  returning with the "repo_root" included in there (see line 95 of lib_repo).  

Therefore, it is double-concatenating the "repo_root".

**Comment by GunnarEngelbach** [comment]
Ah yes, I remember that bug.  I fixed it a long time ago.

Somebody needs to merge my pull request to get these changes.  I'm now 
11 commits ahead of the upstream master -- most of that is for the 
submission_qa.py script.  Which is still a work in progress: right now 
I'm trying to track down problems with determining the minimum schema 
version.

**Comment by adammontville** [comment]
Closing as this one seems fixed - thanks!
