### ISSUE TITLE
oval_decomposition.py doesn't seem to be creating paths when needed

### ISSUE THREAD

**Issue by adammontville** [CISecurity/OVALRepo#68]
I've got an `<oval_definitions>` file containing a single compliance `<definition>` using one test, which uses one object and one state.  When I run `oval_decomposition.py` I receive file not found errors when the path isn't found, though a new file needs to be created.  

For example, when `oval_decomposition.py` needed to create an XML file in `<repository_root>/tests/independent/sql57_test/2000/`, but `sql57_test/2000/` didn't exist, I'd get a `FileNotFoundError`.  

When I manually created the `sql57_test/2000/` bit of the path for the test, I'd get a new `FileNotFoundError` for the object.  Upon fixing that, I'd get a new `FileNotFoundError` for the state, and so on.

In looking at the source for `oval_decomposition.py` and some documentation, could it be the case that the `ElementTree.write()` invocation on line 131 (`tree.write(path, "UTF-8", True)`) expects an open *file* instead of a string path?

**Comment by GunnarEngelbach** [comment]
The destination file doesn't have to exist, but the full path to it 
does, which this script wasn't checking.

I can't tell if that's the problem you are seeing, but it is something 
that definitely needed to be fixed.  Now available in a pull request.

**Comment by adammontville** [comment]
That's the problem I was seeing, and it doesn't appear to be there any longer - thanks for the fix!

**Comment by adammontville** [comment]
I spoke too soon.  It *appears* that things are working, but the reality might be a bit different.  It seems that the path is trying to be created, but with bad permissions precluding any other files from actually being visible.  

For example, `oval_decomposition.py` believes it's added a state file in `<repo_root>/states/independent/sql57_state/2000`, but the `sql57_state` directory (and everything beneath it) is created with `d-wxr----x ` permissions.  This causes a problem when telling git to add changes, as some changes aren't seen. 

So, later when I want to commit to my local topic branch doing `git add .` followed by `git status` shows me one file (the definitions file), but is unable to show me the others because git cannot see them.

**Comment by GunnarEngelbach** [comment]
The python method os.makedirs is supposed to set the permissions as the 
directories are created, but on some operating systems this evidently 
doesn't happen.

I added an explicit os.chmod() after a directory is created (and also 
for files), but that will only help for the last directory in the path.  
If it was necessary to create multiple directories for the full path the 
intermediary ones will still have the less permissive mode.

What is needed is a recursive chmod() function, but until I get a chance 
to make that you should be able to work around it by changing the umask 
for the account you are running these scripts as.

**Comment by adammontville** [comment]
I just checked in a change that set the mode on `os.makedirs` from `755` to `0o755` which seemed to fix the issue.
