### ISSUE TITLE
Function needed for QA

### ISSUE THREAD

**Issue by GunnarEngelbach** [CISecurity/OVALRepo#69]
In order to filter out elements of a submission that are unchanged from what is already in the repository it is necessary to have the contents of the file prior to the submission.

But when a submission is made via a pull request (or oval_decomposition.py is used to put the local repository in the same state for that submission) then the prior version of that file is not available.

Does anybody know how to accomplish that?  Adding that as a function to lib_git would be very helpful.

**Comment by solind** [comment]
I think David Ries already created a function to compare the local Git repo to any remote Git repo, for this exact reason.

**Comment by GunnarEngelbach** [comment]
Since a local commit will not have been performed, the local repository 
will have that information.  Is it not possible to use that to recreate 
the contents of the file prior to the changes made in the working directory?

**Comment by DavidRies** [comment]
The local commit may or may not have been performed (someone may be working on changes). There may have been many local commits as a content contributor is committing part of work, revising a PR, etc.

I think that--bottom line--what we care about is: how does the current working directory (committed or not) compare to the current authoritative branch (i.e. upstream/master or origin/master). That tells us what will change if we commit the current working directly and publish it.

This applies equally well to CIS during a PR review and to a contributor assessing QA'ing work they are doing in any commit state.

That is what I have already implemented. 

- see lib_git.compare_current_oval_to_remote()
- example in find_affected.py

**Comment by DavidRies** [comment]
I marking this closed. Feel free to reopen if lib_git.compare_current_oval_to_remote() is not a solution.
