### ISSUE TITLE
missing test

### ISSUE THREAD

**Issue by geriamir** [CISecurity/OVALRepo#743]
in definition oval:org.cisecurity:def:1870 there's a reference for test oval:com.dtcc:tst:866 which is not in the full windows xml.

**Comment by wmunyan** [comment]
This has been fixed in the repository and will be generated in the downloadable bundles sometime today.  The process refreshes the bundle a couple of times per day, so it could be later in the day by the time this change takes effect.
Cheers, 
-Bill M (CIS)

**Comment by geriamir** [comment]
Well, its also the case on oval:org.cisecurity:def:1869
