### ISSUE TITLE
Consider returning partial matches in repo search

### ISSUE THREAD

**Issue by blakefrantz** [CISecurity/OVALRepo#78]
At this URL:
http://oval.cisecurity.org/repository/search

The ``Id``,  ``Title``, ``Description``, and ``Reference Number`` fields return only exact matches. Consider supporting partial matches.

**Comment by stekel** [comment]
@DavidRies Can we add this ability to the python script?

**Comment by DavidRies** [comment]
Title and description now support partial matches, meaning that if you just enter a word or phrase, it will match any title/description containing that word or phrase. Id and reference are exact matches at this point. I can change these but it would be more work so punting for now.
