### ISSUE TITLE
Index modulus

### ISSUE THREAD

**Issue by blakefrantz** [CISecurity/OVALRepo#79]
The OVAL repo docs provide the following example for where elements should live based on their ID:

``repository/objects/linux/rpminfo_object/24000/oval_org.mitre.oval_obj_23691.xml``

Note that id ``23691`` lives in the ``24000`` folder. Is that ideal?  I expected to find ``23691`` in the ``23000`` folder.  I also expected to find the windows file object having id ``1000`` in the ``1000`` folder, but it lives in the ``2000`` folder. Does that confuse anyone else? Should we change this so, for example, 1000-1999 are in the ``1000`` folder and 20000 - 29999 are in the ``20000`` folder?

**Comment by solind** [comment]
I agree it's confusing!

**Comment by wmunyan** [comment]
Changing that now will require modifications to a few scripts, but it's probably not too too bad.  The remaining question becomes, what about those IDs which are < 1000?  Should they be in a "0" folder?  Or in the main folder for that predicate?  

such as `repository/objects/linux/rpminfo_object/oval_org.mitre.oval_obj_123.xml`

The main folder for the predicate seems less than ideal, but a "0" folder seems even more confusing.

**Comment by wmunyan** [comment]
Agreed on 8/12 transition team call to modify the index modulus calculations
0 <= index <= 999 goes into a folder named "0000"
1000 <= index <= 1999 goes into "1000"
etc etc etc
