### ISSUE TITLE
Should fragments contain a prolog?

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#8]
Each fragment file in the repository contains an prolog like:
````
<?xml version="1.0" encoding="UTF-8"?>
````
Is this going to be a hassle for writers, build scripting, etc. to add/strip? Or, should we keep it?

**Comment by GunnarEngelbach** [comment]
Allowing for the possibility that users will be writing custom code for working with a copy of the repository, I think the XMLDecl should be retained.

**Comment by DavidRies** [comment]
Fine with me. Closing. Feel free to reopen if anyone wants to discuss further.
