### ISSUE TITLE
Invalid XML Error

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#80]
Some of the XML fragments generated by the import process are not valid and are breaking the index import process.

For an example,

```
/repository
  /objects
    /independent
      /environmentvariable58_object
        /16000
          /oval_org.mitre.oval_obj_15638.xml
```

generated the error: 

```
Namespace prefix xsi for nil on pid is not defined, line 3, column 24
```

**Comment by blakefrantz** [comment]
If an xsi namespace is added to the root element of every fragment that uses xsi:nil then,  when those fragments are reassembled, we'll end up with a definitions file that has several in-line xmlns:xsi declarations, unless we specifically remove them.

https://github.com/CISecurity/OVALRepo/blob/master/scripts/set_xsi_namespace.py is a temporary work around.

**Comment by DavidRies** [comment]
Yes, but (I think) this is how we're handling all namespaces. Each fragment has the NS's it uses. When assembled, many NS's are duplicated. But, this is all valid XML and makes maintenance/building easier.

**Comment by wmunyan** [comment]
I have made some modifications to my serialization code to not exclude namespaces, so the initial repo now has namespaces defined for each file, including "xsi".

The issue now needs to focus on the oval_decomposition.py script and ensuring the appropriate namespace declarations are in the generated fragments for contributors.  I am working on this now, and it is currently in-progress.

**Comment by blakefrantz** [comment]
@wmunyan did that also break the build_oval_definitions scripts?

Also, for example, ./tests/independent/textfilecontent_test/2000/oval_org.mitre.oval_tst_1153.xml and many other elements use the "oval-def" namespace.

./tests/independent/textfilecontent_test/2000/oval_org.mitre.oval_tst_1153.xml

**Comment by DavidRies** [comment]
This appears to be fixed.
