### ISSUE TITLE
Incorrect link to OVAL_Repository list

### ISSUE THREAD

**Issue by drothenberg** [CISecurity/OVALRepo#81]
http://oval.cisecurity.org/community/discuss contains a glyph to the left of the OVAL_Repository text that points to http://lists.cisecurity.org/mailman/listinfo/oval_discuss_lists.cisecurity.org. This should instead point to http://lists.cisecurity.org/mailman/listinfo/oval_repository_lists.cisecurity.org

**Comment by stekel** [comment]
fixed.
