### ISSUE TITLE
Script get_repository_stats.py rebuilding the index every run

### ISSUE THREAD

**Issue by stekel** [CISecurity/OVALRepo#82]
The index should only be built from the web_update_indexes.py script.

**Comment by DavidRies** [comment]
Get repository stats was not intended for web and-as you noted-is not safe for concurrent use because it rebuilds the index every time. 

I will make a web_get_repo_stats.py that works like the other web scripts.

**Comment by DavidRies** [comment]
Please use web_get_repository_stats.py which I just created to fix this issue.
