### ISSUE TITLE
Wrong commit - file is not merged /repository/definitions/patch/oval_org.cisecurity_def_2369.xml

### ISSUE THREAD

**Issue by vladimirveselov** [CISecurity/OVALRepo#836]
The file content is not merged:

https://github.com/CISecurity/OVALRepo/blob/0554a959e13889904399a3c232ae986346f4b2f1/repository/definitions/patch/oval_org.cisecurity_def_2369.xml

**Comment by vladimirveselov** [comment]
> grep HEAD /local/tmp/oval/OVALRepo/repository/definitions/patch/*
patch/oval_org.cisecurity_def_2367.xml:<<<<<<< HEAD
patch/oval_org.cisecurity_def_2367.xml:<<<<<<< HEAD
patch/oval_org.cisecurity_def_2368.xml:<<<<<<< HEAD
patch/oval_org.cisecurity_def_2368.xml:<<<<<<< HEAD
patch/oval_org.cisecurity_def_2369.xml:<<<<<<< HEAD
patch/oval_org.cisecurity_def_2369.xml:<<<<<<< HEAD
patch/oval_org.cisecurity_def_2370.xml:<<<<<<< HEAD
patch/oval_org.cisecurity_def_2370.xml:<<<<<<< HEAD
patch/oval_org.cisecurity_def_2371.xml:<<<<<<< HEAD
patch/oval_org.cisecurity_def_2371.xml:<<<<<<< HEAD

**Comment by adammontville** [comment]
Thanks for raising this issue. We have folks presently looking into the correction.

**Comment by adammontville** [comment]
We believe we have made the appropriate fix for this issue. Please reopen if you believe that is not the case. We are also looking into how we avoid this type of problem in the future.
