### ISSUE TITLE
Partially incorrect subtitle on community link description

### ISSUE THREAD

**Issue by drothenberg** [CISecurity/OVALRepo#84]
http://oval.cisecurity.org/community

The subtitle for the "Contribute" link contains the text "submit new definitions" yet points to the https://github.com/OVALProject/Language repository. This is used for maintaining the OVAL Language only. Consider breaking this one option down into the three OVAL repositories:
* https://github.com/OVALProject/Language for the official OVAL Language and any related issues
* https://github.com/OVALProject/Sandbox for experimental features to include in a future OVAL release
* https://github.com/CISecurity/OVALRepo for the new OVAL Repository and submitting new Definitions

**Comment by stekel** [comment]
Urls have been added under the contribute title.
