### ISSUE TITLE
Remove future OVAL release section

### ISSUE THREAD

**Issue by drothenberg** [CISecurity/OVALRepo#85]
http://oval.cisecurity.org/language

With no timeline or set plans for an "OVAL 6.0" version release, perhaps this section should get removed? The descriptor to "Participate in the next version of OVAL on the OVAL Developer’s Forum" would make sense to keep in the "Language Releases" paragraph, but with a fixed link to http://oval.cisecurity.org/community/discuss or http://lists.cisecurity.org/mailman/listinfo/oval_developer_lists.cisecurity.org

**Comment by stekel** [comment]
This section has been removed for now.
