### ISSUE TITLE
Inconsistent URL pattern in default "Download" link

### ISSUE THREAD

**Issue by drothenberg** [CISecurity/OVALRepo#87]
http://oval.cisecurity.org/repository

The default link to the Download page is http://oval.cisecurity.org/repository/download/%7Bversion%7D/%7Bclass%7D where %7B and %7D represent { and } characters. Links from within this page have the format similar to http://oval.cisecurity.org/repository/download/5.11.1/inventory. Consider changing the default URL to http://oval.cisecurity.org/repository/download/.

**Comment by stekel** [comment]
Fixed url on homepage.

I'll update the default url with the current version and default class

**Comment by stekel** [comment]
Default url has been updated
