### ISSUE TITLE
Windows Test to Check for Open Ports

### ISSUE THREAD

**Issue by tagasulat** [CISecurity/OVALRepo#900]
Hi all,

I'm trying to create an OVAL definition that would check if a particular Windows machine can connect to a certain port or if that certain port is open. What test would I use? 

Thanks in advance!

**Comment by SergeyArtykhov** [comment]
Hello @tagasulat ,

Have you tried to use port_test?

Best Regards,
Sergey

**Comment by tagasulat** [comment]
@SergeyArtykhov not yet... i'll try. Thanks!

**Comment by SergeyArtykhov** [comment]
Hello, @tagasulat!

@kemanik has submitted OVAL definition with port_test. We use similar definitions in Windows security compliances.

https://github.com/CISecurity/OVALRepo/pull/909/commits/62cd8b8c183fcb441e0356f02c166a3f1ae88c37

**Comment by tagasulat** [comment]
I've seen it. I appreciate all the help on this. Thanks @SergeyArtykhov and @kemanik!
