### ISSUE TITLE
Error loading glyph icons

### ISSUE THREAD

**Issue by drothenberg** [CISecurity/OVALRepo#91]
Examples on http://oval.cisecurity.org/repository and http://oval.cisecurity.org/community/discuss

Glyphs on the website have difficulty loading on different browsers. See the following image for an example tested within IE and Chrome:

![unknownfont](https://cloud.githubusercontent.com/assets/1615522/9073000/93225f84-3acc-11e5-8220-34c91166f363.png)

These errors are accompanied by the following console log errors:
* Chrome: Font from origin 'https://oval.cisecurity.org' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://oval.cisecurity.org' is therefore not allowed access.
* IE: CSS3117: @font-face failed cross-origin request. Resource access is restricted. File: fontawesome-webfont.eot

I have observed that loading the webpage via HTTPS appears to fix this issue, although any link navigation returns a user to HTTP. Thus, a cache refresh will again break the glyphs.

**Comment by stekel** [comment]
Added some redirection to https, this should now be fixed
